backend:
  name: git-gateway
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "wararka"
    label: "Wararka Cusub"
    folder: "content/news"
    create: true
    fields:
      - {label: "Cinwaanka", name: "title", widget: "string"}
      - {label: "Sawirka Warka", name: "image", widget: "image"}
      - {label: "Qoraalka Warka", name: "body", widget: "markdown"}
